# Generated by Django 4.1.2 on 2022-12-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dz_practical', '0002_alter_posts_create_date_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
