# Generated by Django 4.1.2 on 2022-12-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dz_practical', '0002_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
