# Generated by Django 4.1.2 on 2022-12-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dz_practical', '0003_comments_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='create_date',
            field=models.DateTimeField(),
        ),
    ]
